CREATE DATABASE PBL3
GO
USE PBL3
GO
--Chức năng tự thêm mã hóa đơn
CREATE FUNCTION AUTO_MAHOADON()
RETURNS VARCHAR(10)
AS
BEGIN
	DECLARE @ID VARCHAR(10)
	IF (SELECT COUNT(MaHoaDon) FROM HOADON) = 0
		SET @ID = '0'
	ELSE
		SELECT @ID = MAX(RIGHT(MaHoaDon, 3)) FROM HOADON
		SELECT @ID = CASE
			WHEN @ID >= 0 and @ID < 9 THEN 'HDN000000' + CONVERT(CHAR, CONVERT(INT, @ID) + 1)
			WHEN @ID >= 9 THEN 'HDN00000' + CONVERT(CHAR, CONVERT(INT, @ID) + 1)
			WHEN @ID >= 9 THEN 'HDN0000' + CONVERT(CHAR, CONVERT(INT, @ID) + 1)
			end
	RETURN @ID
END
go

--Chức năng tự thêm mã ca làm
CREATE FUNCTION AUTO_MACALAM()
RETURNS VARCHAR(10)
AS
BEGIN
	DECLARE @ID VARCHAR(10)
	IF (SELECT COUNT(MaCaLam) FROM CALAM) = 0
		SET @ID = '0'
	ELSE
		SELECT @ID = MAX(RIGHT(MaCaLam, 3)) FROM CALAM
		SELECT @ID = CASE
			WHEN @ID >= 0 and @ID < 9 THEN 'CL0000000' + CONVERT(CHAR, CONVERT(INT, @ID) + 1)
			WHEN @ID >= 9 THEN 'CL000000' + CONVERT(CHAR, CONVERT(INT, @ID) + 1)
			WHEN @ID >= 9 THEN 'CL00000' + CONVERT(CHAR, CONVERT(INT, @ID) + 1)
			end
	RETURN @ID
END
go

--Chức năng tự động thêm mã nhà cung ứng
CREATE FUNCTION AUTO_MANCU()
RETURNS VARCHAR(10)
AS
BEGIN
	DECLARE @ID VARCHAR(10)
	IF (SELECT COUNT(MaNhaCungUng) FROM NHACUNGUNG) = 0
		SET @ID = '0'
	ELSE
		SELECT @ID = MAX(RIGHT(MaNhaCungUng, 3)) FROM NHACUNGUNG
		SELECT @ID = CASE
			WHEN @ID >= 0 and @ID < 9 THEN 'NCU000000' + CONVERT(CHAR, CONVERT(INT, @ID) + 1)
			WHEN @ID >= 9 THEN 'NCU00000' + CONVERT(CHAR, CONVERT(INT, @ID) + 1)
			WHEN @ID >= 9 THEN 'NCU0000' + CONVERT(CHAR, CONVERT(INT, @ID) + 1)
			end
	RETURN @ID
END
go

--Chức năng tự động thêm mã đề xuất
CREATE FUNCTION AUTO_MADEXUAT()
RETURNS VARCHAR(10)
AS
BEGIN
	DECLARE @ID VARCHAR(10)
	IF (SELECT COUNT(MaDeXuat) FROM DEXUAT) = 0
		SET @ID = '0'
	ELSE
		SELECT @ID = MAX(RIGHT(MaDeXuat, 3)) FROM DEXUAT
		SELECT @ID = CASE
			WHEN @ID >= 0 and @ID < 9 THEN 'DX0000000' + CONVERT(CHAR, CONVERT(INT, @ID) + 1)
			WHEN @ID >= 9 THEN 'DX000000' + CONVERT(CHAR, CONVERT(INT, @ID) + 1)
			WHEN @ID >= 9 THEN 'DX00000' + CONVERT(CHAR, CONVERT(INT, @ID) + 1)
			end
	RETURN @ID
END
go

--Chức năng tự động thêm mã hợp đồng NCU
CREATE FUNCTION AUTO_MAHOPDONGNCU()
RETURNS VARCHAR(10)
AS
BEGIN
	DECLARE @ID VARCHAR(10)
	IF (SELECT COUNT(MaHopDongNCU) FROM HOPDONGNHACUNGUNG) = 0
		SET @ID = '0'
	ELSE
		SELECT @ID = MAX(RIGHT(MaHopDongNCU, 3)) FROM HOPDONGNHACUNGUNG
		SELECT @ID = CASE
			WHEN @ID >= 0 and @ID < 9 THEN 'HDNCU0000' + CONVERT(CHAR, CONVERT(INT, @ID) + 1)
			WHEN @ID >= 9 THEN 'HDNCU000' + CONVERT(CHAR, CONVERT(INT, @ID) + 1)
			WHEN @ID >= 9 THEN 'HDNCU00' + CONVERT(CHAR, CONVERT(INT, @ID) + 1)
			end
	RETURN @ID
END
go

--Chức năng tự động thêm mã hợp đồng Nhân viên
CREATE FUNCTION AUTO_MAHOPDONGNV()
RETURNS VARCHAR(10)
AS
BEGIN
	DECLARE @ID VARCHAR(10)
	IF (SELECT COUNT(MaHopDongNV) FROM HOPDONGNHANVIEN) = 0
		SET @ID = '0'
	ELSE
		SELECT @ID = MAX(RIGHT(MaHopDongNV, 3)) FROM HOPDONGNHANVIEN
		SELECT @ID = CASE
			WHEN @ID >= 0 and @ID < 9 THEN 'HDNV00000' + CONVERT(CHAR, CONVERT(INT, @ID) + 1)
			WHEN @ID >= 9 THEN 'HDNV0000' + CONVERT(CHAR, CONVERT(INT, @ID) + 1)
			WHEN @ID >= 9 THEN 'HDNV000' + CONVERT(CHAR, CONVERT(INT, @ID) + 1)
			end
	RETURN @ID
END
go

--Chức năng tự động thêm mã phản hồi
CREATE FUNCTION AUTO_MAPHANHOI()
RETURNS VARCHAR(10)
AS
BEGIN
	DECLARE @ID VARCHAR(10)
	IF (SELECT COUNT(MaPhanHoi) FROM PHANHOI) = 0
		SET @ID = '0'
	ELSE
		SELECT @ID = MAX(RIGHT(MaPhanHoi, 3)) FROM PHANHOI
		SELECT @ID = CASE
			WHEN @ID >= 0 and @ID < 9 THEN 'PH0000000' + CONVERT(CHAR, CONVERT(INT, @ID) + 1)
			WHEN @ID >= 9 THEN 'PH000000' + CONVERT(CHAR, CONVERT(INT, @ID) + 1)
			WHEN @ID >= 9 THEN 'PH00000' + CONVERT(CHAR, CONVERT(INT, @ID) + 1)
			end
	RETURN @ID
END
go

--Chức năng tự thêm mã chương trình khuyến mãi
CREATE FUNCTION AUTO_MAKHUYENMAI()
RETURNS VARCHAR(10)
AS
BEGIN
	DECLARE @ID VARCHAR(10)
	IF (SELECT COUNT(MaKhuyenMai) FROM KHUYENMAI) = 0
		SET @ID = '0'
	ELSE
		SELECT @ID = MAX(RIGHT(MaKhuyenMai, 3)) FROM KHUYENMAI
		SELECT @ID = CASE
			WHEN @ID >= 0 and @ID < 9 THEN 'KM0000000' + CONVERT(CHAR, CONVERT(INT, @ID) + 1)
			WHEN @ID >= 9 THEN 'KM000000' + CONVERT(CHAR, CONVERT(INT, @ID) + 1)
			WHEN @ID >= 9 THEN 'KM00000' + CONVERT(CHAR, CONVERT(INT, @ID) + 1)
			end
	RETURN @ID
END
go

--Chức năng tự thêm mã nhân viên
CREATE FUNCTION AUTO_MANHANVIEN()
RETURNS VARCHAR(10)
AS
BEGIN
	DECLARE @ID VARCHAR(10)
	IF (SELECT COUNT(MaNhanVien) FROM NHANVIEN) = 0
		SET @ID = '0'
	ELSE
		SELECT @ID = MAX(RIGHT(MaNhanVien, 3)) FROM NHANVIEN
		SELECT @ID = CASE
			WHEN @ID >= 0 and @ID < 9 THEN 'NV0000000' + CONVERT(CHAR, CONVERT(INT, @ID) + 1)
			WHEN @ID >= 9 THEN 'NV000000' + CONVERT(CHAR, CONVERT(INT, @ID) + 1)
			WHEN @ID >= 9 THEN 'NV00000' + CONVERT(CHAR, CONVERT(INT, @ID) + 1)
			end
	RETURN @ID
END
go

CREATE FUNCTION AUTO_MAKHUTRUNGBAY()
RETURNS VARCHAR(10)
AS
BEGIN
	DECLARE @ID VARCHAR(10)
	IF (SELECT COUNT(MaKhuTrungBay) FROM KHUTRUNGBAY) = 0
		SET @ID = '0'
	ELSE
		SELECT @ID = MAX(RIGHT(MaKhuTrungBay, 3)) FROM KHUTRUNGBAY
		SELECT @ID = CASE
			WHEN @ID >= 0 and @ID < 9 THEN 'KTB000000' + CONVERT(CHAR, CONVERT(INT, @ID) + 1)
			WHEN @ID >= 9 THEN 'KTB00000' + CONVERT(CHAR, CONVERT(INT, @ID) + 1)
			WHEN @ID >= 9 THEN 'KTB0000' + CONVERT(CHAR, CONVERT(INT, @ID) + 1)
			end
		RETURN @ID
END
GO

CREATE FUNCTION AUTO_MATHELOAIHANGHOA()
RETURNS VARCHAR(10)
AS
BEGIN
	DECLARE @ID VARCHAR(10)
	IF (SELECT COUNT(MaTheLoaiHangHoa) FROM THELOAIHANGHOA) = 0
		SET @ID = '0'
	ELSE
		SELECT @ID = MAX(RIGHT(MaTheLoaiHangHoa, 3)) FROM THELOAIHANGHOA
		SELECT @ID = CASE
			WHEN @ID >= 0 and @ID < 9 THEN 'TLHH00000' + CONVERT(CHAR, CONVERT(INT, @ID) + 1)
			WHEN @ID >= 9 THEN 'TLHH0000' + CONVERT(CHAR, CONVERT(INT, @ID) + 1)
			WHEN @ID >= 9 THEN 'THLL000' + CONVERT(CHAR, CONVERT(INT, @ID) + 1)
			end
		RETURN @ID
END
GO

CREATE FUNCTION AUTO_MATHELOAISACH()
RETURNS VARCHAR(10)
AS
BEGIN
	DECLARE @ID VARCHAR(10)
	IF (SELECT COUNT(MaTheLoaiSach) FROM THELOAISACH) = 0
		SET @ID = '0'
	ELSE
		SELECT @ID = MAX(RIGHT(MaTheLoaiSach, 3)) FROM THELOAISACH
		SELECT @ID = CASE
			WHEN @ID >= 0 and @ID < 9 THEN 'TLS000000' + CONVERT(CHAR, CONVERT(INT, @ID) + 1)
			WHEN @ID >= 9 THEN 'TLS00000' + CONVERT(CHAR, CONVERT(INT, @ID) + 1)
			WHEN @ID >= 9 THEN 'TLS0000' + CONVERT(CHAR, CONVERT(INT, @ID) + 1)
			end
		RETURN @ID
END
GO

CREATE FUNCTION AUTO_MAHANGHOA()
RETURNS VARCHAR(10)
AS
BEGIN
	DECLARE @ID VARCHAR(10)
	IF (SELECT COUNT(MaHangHoa) FROM HANGHOA) = 0
		SET @ID = '0'
	ELSE
		SELECT @ID = MAX(RIGHT(MaHangHoa, 3)) FROM HANGHOA
		SELECT @ID = CASE
			WHEN @ID >= 0 and @ID < 9 THEN 'HH0000000' + CONVERT(CHAR, CONVERT(INT, @ID) + 1)
			WHEN @ID >= 9 THEN 'HH000000' + CONVERT(CHAR, CONVERT(INT, @ID) + 1)
			WHEN @ID >= 9 THEN 'HH00000' + CONVERT(CHAR, CONVERT(INT, @ID) + 1)
			end
		RETURN @ID
END
GO

CREATE FUNCTION AUTO_MASACH()
RETURNS VARCHAR(10)
AS
BEGIN
	DECLARE @ID VARCHAR(10)
	IF (SELECT COUNT(MaSach) FROM SACH) = 0
		SET @ID = '0'
	ELSE
		SELECT @ID = MAX(RIGHT(MaSach, 3)) FROM SACH
		SELECT @ID = CASE
			WHEN @ID >= 0 and @ID < 9 THEN 'S000000000' + CONVERT(CHAR, CONVERT(INT, @ID) + 1)
			WHEN @ID >= 9 THEN 'S0000000 ' + CONVERT(CHAR, CONVERT(INT, @ID) + 1)
			WHEN @ID >= 9 THEN 'S000000' + CONVERT(CHAR, CONVERT(INT, @ID) + 1)
			end
		RETURN @ID
END
GO


CREATE TABLE KHO
(
    MaKho VARCHAR(10) NOT NULL,
	TenKho NVARCHAR(50),
	TrangThai NVARCHAR(20) 
		CHECK(TrangThai IN (N'Đang hoạt động', N'Đầy', N'Tạm ngưng')),
	CONSTRAINT PK_KHO PRIMARY KEY (MaKho),
)

CREATE TABLE KHUTRUNGBAY
(
	MaKhuTrungBay VARCHAR(10) NOT NULL DEFAULT [dbo].AUTO_MAKHUTRUNGBAY(),
	TenKhuTrungBay NVARCHAR(50),
	SoLuongToiDa SMALLINT,
	CONSTRAINT PK_KHUTRUNGBAY PRIMARY KEY (MaKhuTrungBay),
)

CREATE TABLE THELOAIHANGHOA
(
	MaTheLoaiHangHoa VARCHAR(10) NOT NULL DEFAULT [dbo].AUTO_MATHELOAIHANGHOA(),
	TenTheLoaiHangHoa NVARCHAR(50),
	CONSTRAINT PK_THELOAIHANGHOA PRIMARY KEY (MaTheLoaiHangHoa),

)

CREATE TABLE THELOAISACH
(
	MaTheLoaiSach VARCHAR(10) NOT NULL DEFAULT [dbo].AUTO_MATHELOAISACH(),
	TenTheLoaiSach NVARCHAR(50),
	CONSTRAINT PK_THELOAISACH PRIMARY KEY (MaTheLoaiSach),
)


CREATE TABLE NHACUNGUNG
(
	MaNhaCungUng VARCHAR(10) PRIMARY KEY NOT NULL CONSTRAINT df_MCL DEFAULT [dbo].AUTO_MANCU(),
	TenNhaCungUng NVARCHAR(50),
	TenNguoiDaiDienPhapLy NVARCHAR(30),
	TenNguoiDaiDienKinhDoanh NVARCHAR(30),
	DiaChi NVARCHAR(150),
	SoDienThoai CHAR(10)
		CHECK (SoDienThoai LIKE '[0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9]'),
	TrangThai NVARCHAR(20)
		CHECK (TrangThai IN (N'Đang hoạt động',N'Không hoạt động')),
	)

/*CREATE TABLE HOPDONG
(
	MaHopDong VARCHAR(10) NOT NULL,
	LoaiHopDong NVARCHAR(23)
		CHECK (LoaiHopDong IN (N'Hợp đồng nhân viên', N'Hợp đồng nhà cung ứng')),
	CONSTRAINT PK_HOPDONG PRIMARY KEY (MaHopDong),
)*/


	--Xóa khóa ngoại mã hợp đồng vì đã bỏ bảng hợp đồng, cho Mã hợp đồng tự động tăng
CREATE TABLE HOPDONGNHACUNGUNG  --SỬA
(
	MaHopDongNCU VARCHAR(10) PRIMARY KEY NOT NULL CONSTRAINT df_MHDNCU DEFAULT [dbo].AUTO_MAHOPDONGNCU(),
	MaNhaCungUng VARCHAR(10) FOREIGN KEY REFERENCES NHACUNGUNG (MaNhaCungUng),
	NgayBatDau DATE,
	NgayKetThuc DATE,
	HinhAnh IMAGE NULL,
	--CONSTRAINT PK_HOPDONGNHACUNGUNG PRIMARY KEY (MaHopDong),
)

CREATE TABLE HANGHOA
(
	MaHangHoa VARCHAR(10) NOT NULL DEFAULT [dbo].AUTO_MAHANGHOA(),
	TenHangHoa NVARCHAR(50),
	MaTheLoaiHangHoa VARCHAR(10) FOREIGN KEY REFERENCES THELOAIHANGHOA(MaTheLoaiHangHoa),
	NhaSanXuat NVARCHAR(50),
	MaNhaCungUng VARCHAR(10) FOREIGN KEY REFERENCES NHACUNGUNG(MaNhaCungUng),
	NamSanXuat CHAR(4)
		CHECK (NamSanXuat LIKE '[0-9][0-9][0-9][0-9]'),
	MaKhuTrungBay VARCHAR(10) FOREIGN KEY REFERENCES KHUTRUNGBAY(MaKhuTrungBay),
	SoLuongTrenKhuTrungBay SMALLINT,
	MaKho VARCHAR(10) FOREIGN KEY REFERENCES KHO(MaKho),
	SoLuongTrongKho SMALLINT,
	GiaNhap DECIMAL(10, 0),
	GiaBan DECIMAL(10, 0),
	TrangThai NVARCHAR(40)
		CHECK (TrangThai IN (N'',N'Đang kinh doanh', N'Đang chờ xét duyệt thêm', N'Đang chờ xét duyệt tạm ngừng kinh doanh', N'Đang chờ xét duyệt cập nhật thông tin', N'Tạm ngừng kinh doanh')),
	CONSTRAINT PK_HANGHOA PRIMARY KEY (MaHangHoa),
)

CREATE TABLE SACH
(
	MaSach VARCHAR(10) NOT NULL DEFAULT [dbo].AUTO_MASACH(),
	TacGia NVARCHAR(30),
	LanTaiBan TINYINT,
	MaHangHoa VARCHAR(10) FOREIGN KEY REFERENCES HANGHOA (MaHangHoa),
	MaTheLoaiSach VARCHAR(10) FOREIGN KEY REFERENCES THELOAISACH (MaTheLoaiSach),
	CONSTRAINT PK_SACH PRIMARY KEY (MaSach),
)


CREATE TABLE KHUYENMAI
(
	MaKhuyenMai VARCHAR(10) PRIMARY KEY NOT NULL CONSTRAINT df_MKM DEFAULT [dbo].AUTO_MAKHUYENMAI(),
	TenChuongTrinhKhuyenMai NVARCHAR(50),
	MaHangHoa VARCHAR(10) FOREIGN KEY REFERENCES HANGHOA(MaHangHoa),
	PhanTramKhuyenMai TINYINT 
		CHECK (PhanTramKhuyenMai >=0 AND PhanTramKhuyenMai <= 100),
	NgayBatDau DATE,
	NgayKetThuc DATE,
	--CONSTRAINT PK_KHUYENMAI PRIMARY KEY (MaKhuyenMai),
)

CREATE TABLE CHUCVU
(
	MaChucVu VARCHAR(10) NOT NULL,
	TenChucVu NVARCHAR(20),
	PhuCapChucVu INT,
	CONSTRAINT PK_CHUCVU PRIMARY KEY (MaChucVu),
)

CREATE TABLE CALAM
(
	
	MaCaLam VARCHAR(10) PRIMARY KEY NOT NULL CONSTRAINT df_MCAuto DEFAULT [dbo].AUTO_MACALAM(),
	TenCaLam NVARCHAR(20),
	GioBatDau TIME,
	GioKetThuc TIME,
	PhuCapCaLam INT,
	TrangThai NVARCHAR(20)
		CHECK (TrangThai IN (N'Hoạt động', N'Tạm ngưng')),
)

CREATE TABLE NHANVIEN
(
	
	MaNhanVien VARCHAR(10) PRIMARY KEY NOT NULL CONSTRAINT df_MNV DEFAULT [dbo].AUTO_MANHANVIEN(),
	TenNhanVien NVARCHAR(30),
	GioiTinh BIT,
	NgaySinh DATE,
	SoCanCuocCongDan CHAR(12)
		CHECK (SoCanCuocCongDan LIKE '[0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9]'),
	SoDienThoai CHAR(10)
		CHECK (SoDienThoai LIKE '[0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9]'),
	DiaChi NVARCHAR(150),
	--CONSTRAINT PK_NHANVIEN PRIMARY KEY (MaNhanVien),
	MaChucVu VARCHAR(10) FOREIGN KEY REFERENCES CHUCVU (MaChucVu),
	TinhTrang NVARCHAR(50)
		CHECK (TinhTrang IN (N'Hoạt động', N'Tạm ngưng')),
)

--Xóa khóa ngoại mã hợp đồng vì đã bỏ bảng hợp đồng, cho Mã hợp đồng tự động tăng
CREATE TABLE HOPDONGNHANVIEN  --SỬA
(
	MaHopDongNV VARCHAR(10) PRIMARY KEY NOT NULL CONSTRAINT df_MHDNV DEFAULT [dbo].AUTO_MAHOPDONGNV() ,
	MaNhanVien VARCHAR(10) FOREIGN KEY REFERENCES NHANVIEN(MaNhanVien),
	NgayKy DATE,
	HinhAnh IMAGE,
	--CONSTRAINT PK_HOPDONGNHANVIEN PRIMARY KEY (MaHopDong, MaNhanVien),
)

CREATE TABLE CHITIETCALAM
(
	MaCaLam VARCHAR(10) FOREIGN KEY REFERENCES CALAM (MaCaLam),
	MaNhanVien VARCHAR(10) FOREIGN KEY REFERENCES NHANVIEN (MaNhanVien),
	TrangThai NVARCHAR(30) 
		CHECK (TrangThai IN (N'Đang làm việc', N'Tạm ngưng')),
	CONSTRAINT PK_CHITIETCALAM PRIMARY KEY (MaCaLam, MaNhanVien),
	
)

/*Vẫn chưa đặt khóa ngoại được*/
CREATE TABLE LUONG
(
	MaLuong VARCHAR(10) NOT NULL,
	MaNhanvien VARCHAR(10),
	MaCaLam VARCHAR(10),
	MaChucVu VARCHAR(10),
	TienLuong INT,
	CONSTRAINT PK_LUONG PRIMARY KEY (MaLuong)
	/*CONSTRAINT FK_LUONG_NHANVIEN FOREIGN KEY (MaNhanVien, MaChucVu) REFERENCES NHANVIEN (MaNhanVien, MaChucVu),*/
	/*CONSTRAINT FK_LUONG_CHITIETCALAM FOREIGN KEY (MaNhanVien, MaCaLam) REFERENCES CHITIETCALAM (PK_CHITIETCALAM),*/
)

CREATE TABLE TAIKHOAN
(
	TenTaiKhoan VARCHAR(50) NOT NULL,
	MatKhau VARCHAR(50) NOT NULL,
	MaNhanVien VARCHAR(10) FOREIGN KEY REFERENCES NHANVIEN(MaNhanVien),
	CONSTRAINT PK_TAIKHOAN PRIMARY KEY (TenTaiKhoan),
)




CREATE TABLE HOADON
(
	MaHoaDon VARCHAR(10) PRIMARY KEY NOT NULL CONSTRAINT df_MHD DEFAULT [dbo].AUTO_MAHOADON(),
	ThoiGian DATETIME,
	MaNhanVien VARCHAR(10) FOREIGN KEY REFERENCES NHANVIEN(MaNhanvien),
	TongTien Decimal(10,3)
	
)

CREATE TABLE CHITIETHOADON
(
	MaHoaDon VARCHAR(10) FOREIGN KEY REFERENCES HOADON(MaHoaDon),
	MaHangHoa VARCHAR(10) FOREIGN KEY REFERENCES HANGHOA(MaHangHoa),
	SoLuong SMALLINT,
	CONSTRAINT PK_CHITIETHOADON PRIMARY KEY (MaHoaDon, MaHangHoa),
)

CREATE TABLE DEXUAT
(
	MaDeXuat VARCHAR(10) PRIMARY KEY NOT NULL CONSTRAINT df_MDX DEFAULT [dbo].AUTO_MADEXUAT(),
	MaNhanVien VARCHAR(10)  FOREIGN KEY REFERENCES NHANVIEN(MaNhanVien),
	TinhTrang NVARCHAR(20)
		CHECK (TinhTrang IN (N'Đang chờ phê duyệt', N'Chấp nhận', N'Không chấp nhận')),
	LoaiDeXuat NVARCHAR(40)
		CHECK (LoaiDeXuat IN (N'Đề xuất thêm nhà cung ứng', N'Đề xuất thêm hàng hóa', N'Đề xuất nhập hàng hóa vào kho', N'Đề xuất xuất hàng hóa lên kệ', N'Đề xuất tạm ngừng kinh doanh hàng hóa', N'Đề xuất cập nhật thông tin hàng hóa', N'Đề xuất cập nhật thông tin nhà cung ứng')),
	ThoiGian DATETIME,
	
)
CREATE TABLE PHANHOI
(
	MaPhanHoi VARCHAR(10) PRIMARY KEY NOT NULL CONSTRAINT df_MPH DEFAULT [dbo].AUTO_MAPHANHOI(),
	MaNhanVien VARCHAR(10) FOREIGN KEY REFERENCES NHANVIEN (MaNhanVien),
	MaDeXuat VARCHAR(10) FOREIGN KEY REFERENCES DEXUAT (MaDeXuat),
	ThoiGian DATETIME,
	NoiDung NTEXT,
	--CONSTRAINT PK_PHANHOI PRIMARY KEY (MaPhanHoi),
)

CREATE TABLE CHITIETDEXUATHANGHOA
(
	MaDeXuat VARCHAR(10) FOREIGN KEY REFERENCES DEXUAT(MaDeXuat),
	MaHangHoa VARCHAR(10) FOREIGN KEY REFERENCES HANGHOA(MaHangHoa),

	MaThamChieu VARCHAR(10),
	CONSTRAINT PK_CHITIETDEXUATHANGHOA PRIMARY KEY (MaDeXuat, MaHangHoa),
)

CREATE TABLE CHITIETDEXUATNHACUNGUNG
(
	MaDeXuat VARCHAR(10) FOREIGN KEY REFERENCES DEXUAT(MaDeXuat),
	MaNhaCungUng VARCHAR(10) FOREIGN KEY REFERENCES NHACUNGUNG(MaNhaCungUng),
	MaThamChieu VARCHAR(10),
	CONSTRAINT PK_CHITIETDEXUATNHACUNGUNG PRIMARY KEY (MaDeXuat, MaNhaCungUng),
)

CREATE TABLE CHITIETDEXUATHOADON
(
	MaDeXuat VARCHAR(10) FOREIGN KEY REFERENCES DEXUAT(MaDeXuat),
	MaHangHoa VARCHAR(10) FOREIGN KEY REFERENCES HANGHOA(MaHangHoa),
	SoLuong SMALLINT,
	CONSTRAINT PK_CHITIETDEXUATHOADON PRIMARY KEY (MaDeXuat, MaHangHoa),
)